<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="nitunp-L" name="testCases.TC_Login" tests="1" failures="0" timestamp="25 Oct 2016 09:36:31 GMT" time="39.272" errors="1">
  <testcase name="TC_login" time="39.272" classname="testCases.TC_Login">
    <error type="java.io.FileNotFoundException" message="no such entry: &quot;EncryptionInfo&quot;, had: [SummaryInformation, DocumentSummaryInformation, Workbook]">
      <![CDATA[java.io.FileNotFoundException: no such entry: "EncryptionInfo", had: [SummaryInformation, DocumentSummaryInformation, Workbook]
	at org.apache.poi.poifs.filesystem.DirectoryNode.getEntry(DirectoryNode.java:399)
	at org.apache.poi.poifs.filesystem.DirectoryNode.createDocumentInputStream(DirectoryNode.java:188)
	at org.apache.poi.poifs.crypt.EncryptionInfo.<init>(EncryptionInfo.java:94)
	at org.apache.poi.poifs.crypt.EncryptionInfo.<init>(EncryptionInfo.java:88)
	at utils.ExcelConnection.getEmailExcelPOI(ExcelConnection.java:68)
	at testCases.TC_Login.TC_login(TC_Login.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- TC_login -->
</testsuite> <!-- testCases.TC_Login -->
